### ISSUE TITLE
After clicking on login this error came **_firebase__WEBPACK_IMPORTED_MODULE_7__.default.collection is not a function

### ISSUE THREAD

**Issue by IShubh-10** [CleverProgrammers/cp-disney-plus-clone#26]
After clicking on login the below error came 
Uncaught runtime errors:
×
ERROR
**_firebase__WEBPACK_IMPORTED_MODULE_7__.default.collection is not a function
TypeError: _firebase__WEBPACK_IMPORTED_MODULE_7__.default.collection is not a function**
    at http://localhost:3000/static/js/bundle.js:1093:55
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:73420:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:74913:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:74885:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:74875:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:74865:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:76748:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:76701:18)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/bundle.js:75918:7)
    at flushSyncCallbacks (http://localhost:3000/static/js/bundle.js:63927:26)

**Comment by IShubh-10** [comment]
Everything is solved and website working fine.
